version: "3.8"

services:
  app:
    build:
      context: ./app
      target: dev
    volumes:
      - ./app:/workspaces/app
    env_file:
      - ./app/.env
    container_name: nextjs-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    expose:
      - "3000"  # 内部で使用
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_ENV: dev
    container_name: nginx-proxy
    ports:
      - "8080:80"  # ホスト → Nginx
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sampledb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
